// apps/react-mfe/src/index.js
import React from "react";
import { createRoot } from "react-dom/client";
import "./styles.css";

function App() {
  return (
    <main className="react-mfe-preview">
      <h1>React MFE Remote</h1>
      <p>This app exposes Module Federation modules and a Header web component.</p>
    </main>
  );
}

const rootContainer = document.getElementById("root");
if (rootContainer) {
  createRoot(rootContainer).render(<App />);
}

// apps/angular-mfe/src/index.ts
import { Component } from "@angular/core";
import { bootstrapApplication } from "@angular/platform-browser";
import "./polyfills";
import "./styles.css";

@Component({
  standalone: true,
  selector: "angular-preview-root",
  template: `
    <main class="angular-preview">
      <h1>Angular MFE Domain</h1>
      <p>
        This app exposes product components through Module Federation and provides
        an iframe page for Order Placed.
      </p>
    </main>
  `,
})
class AngularPreviewComponent {}

if (document.getElementById("root")) {
  bootstrapApplication(AngularPreviewComponent);
}
